/**
 * ML Training Corpus — Type Definitions & Utilities
 *
 * This is the ML training corpus for future Phase 8.6 features (predictive
 * load development, anomaly detection, powder-burn modelling, etc.).
 *
 * Data is CC0-licensed, contributed by the GRT (Gordon's Reloading Tool)
 * community Discord. Community-contributed data must be verified independently
 * before use in safety-critical calculations.
 *
 * The backing JSON file (`training-data.json`) is generated by
 * `scripts/parse-grt.mjs` — do not edit it manually.
 */

// ---------------------------------------------------------------------------
// Interfaces
// ---------------------------------------------------------------------------

export interface DualUnit {
  mm: number;
  in: number;
}

export interface PressureUnit {
  bar: number;
  psi: number;
}

export interface TrainingProjectile {
  manufacturer: string;
  productName: string;
  caliber: string;           // e.g. ".224"
  grooveDiameter: DualUnit;
  length: DualUnit;
  mass: { gr: number };
  engravingPressure: PressureUnit;
  tailDiameterA: DualUnit;
  tailDiameterB: DualUnit;
  tailHeight: DualUnit;
  tailType: number;
  g1bc: number;
  g7bc: number;
  ubcsCode: string;          // Universal Bullet Classification Scheme
  createdDate: string;
  createdBy: string;
  description: string;
  _source: string;
}

export interface TrainingPowder {
  manufacturer: string;
  productName: string;
  lotId: string;
  progressivityFactor: number;     // Bp
  brisanceFactor: number;          // Br
  combinedBrisanceProgressivity: number; // Brp
  vivacityCoefficient: number;     // Ba
  specificExplosiveHeat_kJkg: number; // Qex
  specificHeatRatio: number;       // k
  baPhiCoefficient: number;        // Ba(phi)
  burnUpLimitZ1: number;           // z1
  burnUpLimitZ2: number;           // z2
  covolume_cm3g: number;           // eta
  materialDensity_kgm3: number;
  bulkDensity_kgm3: number;
  temperature_C: number;
  coldTempCoefficient: number;
  hotTempCoefficient: number;
  createdDate: string;
  createdBy: string;
  description: string;
  _source: string;
}

export interface TrainingCaliber {
  cipName: string;
  altName: string;
  standard: string;
  cipOrigin: string;
  cipType: string;
  cipDate: string;
  caseLength: DualUnit;
  overallLength: DualUnit;
  caseHeadRadius: DualUnit;
  rimDiameter: DualUnit;
  neckWallThickness: DualUnit;
  bodyDiameter: DualUnit;
  minNeckThickness: DualUnit;
  maxPressure: PressureUnit;
  proofPressurePK: PressureUnit;
  proofPressurePE: PressureUnit;
  caseVolume: number;         // cm3
  caseWeight: number;         // grams
  sebertFactor: number;
  boreArea_mm2: number;
  grooveCount: number;
  twistRate: DualUnit;
  createdDate: string;
  createdBy: string;
  description: string;
  _source: string;
}

export interface TrainingLoad {
  caliber: {
    name: string;
    overallLength: DualUnit;
    caseLength: DualUnit;
    caseVolume_cm3: number;
    grooveCaliber: DualUnit;
    effectiveArea_mm2: number;
    maxPressure: PressureUnit;
  };
  gun: {
    barrelLength: DualUnit;
    twistRate: DualUnit;
    weight_kg: number;
  };
  projectile: {
    manufacturer: string;
    productName: string;
    diameter: DualUnit;
    weight: { g: number; gr: number };
    length: DualUnit;
    g1bc: number;
    g7bc: number;
    engravingPressure: PressureUnit;
  };
  propellant: {
    manufacturer: string;
    productName: string;
    vivacityCoefficient: number;
    specificExplosiveHeat_kJkg: number;
    specificHeatRatio: number;
    baPhiCoefficient: number;
    burnUpLimitZ1: number;
    burnUpLimitZ2: number;
    covolume_cm3g: number;
    materialDensity_kgm3: number;
    bulkDensity_kgm3: number;
    chargeMass: { g: number; gr: number };
    temperature_C: number;
    coldTempCoefficient: number;
    hotTempCoefficient: number;
  };
  _source: string;
}

export interface TrainingCorpus {
  meta: {
    source: string;
    sourceUrl: string;
    license: string;
    disclaimer: string;
    parsedAt: string;
    counts: {
      projectiles: number;
      powders: number;
      calibers: number;
      loads: number;
    };
  };
  projectiles: TrainingProjectile[];
  powders: TrainingPowder[];
  calibers: TrainingCaliber[];
  loads: TrainingLoad[];
}

// ---------------------------------------------------------------------------
// Data loading
// ---------------------------------------------------------------------------

// Import the parsed JSON (generated by scripts/parse-grt.mjs)
import corpusData from "./training-data.json";

export const TRAINING_CORPUS: TrainingCorpus = corpusData as TrainingCorpus;

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

/** Find projectiles by caliber designation (exact match). */
export function findProjectilesByCaliber(
  caliber: string,
): TrainingProjectile[] {
  return TRAINING_CORPUS.projectiles.filter((p) => p.caliber === caliber);
}

/** Find powders by manufacturer (exact match). */
export function findPowdersByManufacturer(
  manufacturer: string,
): TrainingPowder[] {
  return TRAINING_CORPUS.powders.filter((p) => p.manufacturer === manufacturer);
}

/** Find calibers by name (partial match, case-insensitive). */
export function findCalibersByName(query: string): TrainingCaliber[] {
  const lowerQuery = query.toLowerCase();
  return TRAINING_CORPUS.calibers.filter(
    (c) =>
      c.cipName.toLowerCase().includes(lowerQuery) ||
      c.altName.toLowerCase().includes(lowerQuery),
  );
}

/** Get all unique caliber designations from the projectile table. */
export function getUniqueCalibers(): string[] {
  return [...new Set(TRAINING_CORPUS.projectiles.map((p) => p.caliber))].sort();
}

/** Get all unique powder manufacturers. */
export function getUniquePowderManufacturers(): string[] {
  return [
    ...new Set(TRAINING_CORPUS.powders.map((p) => p.manufacturer)),
  ].sort();
}

/** Get a high-level summary of the training corpus. */
export function getCorpusSummary(): {
  totalRecords: number;
  projectileCount: number;
  powderCount: number;
  caliberCount: number;
  loadCount: number;
  uniqueCalibers: string[];
  uniquePowderManufacturers: string[];
  uniqueProjectileManufacturers: string[];
} {
  const projectileCount = TRAINING_CORPUS.projectiles.length;
  const powderCount = TRAINING_CORPUS.powders.length;
  const caliberCount = TRAINING_CORPUS.calibers.length;
  const loadCount = TRAINING_CORPUS.loads.length;

  return {
    totalRecords: projectileCount + powderCount + caliberCount + loadCount,
    projectileCount,
    powderCount,
    caliberCount,
    loadCount,
    uniqueCalibers: getUniqueCalibers(),
    uniquePowderManufacturers: getUniquePowderManufacturers(),
    uniqueProjectileManufacturers: [
      ...new Set(TRAINING_CORPUS.projectiles.map((p) => p.manufacturer)),
    ].sort(),
  };
}
